import { UserRole } from '@prisma/client';

import {
  Permission,
  PERMISSIONS,
} from './permissions';

export const ROLE_PERMISSIONS: Record<
  UserRole,
  Permission[]
> = {
  [UserRole.SUPER_ADMIN]: Object.values(
    PERMISSIONS,
  ),

  [UserRole.COMPANY_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_UPDATE,

    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,

    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.WAREHOUSE_CREATE,
    PERMISSIONS.WAREHOUSE_UPDATE,
    PERMISSIONS.WAREHOUSE_DELETE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_DELETE,

    PERMISSIONS.RECORDING_VIEW,
    PERMISSIONS.RECORDING_CREATE,

    PERMISSIONS.EVIDENCE_VIEW,

    PERMISSIONS.CLAIM_VIEW,
    PERMISSIONS.CLAIM_UPDATE,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_UPDATE,
  ],

  [UserRole.WAREHOUSE_MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.USER_VIEW,

    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.WAREHOUSE_UPDATE,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.RECORDING_VIEW,
    PERMISSIONS.RECORDING_CREATE,

    PERMISSIONS.EVIDENCE_VIEW,

    PERMISSIONS.CLAIM_VIEW,

    PERMISSIONS.REPORT_VIEW,
  ],

  [UserRole.SUPERVISOR]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.ORDER_UPDATE,

    PERMISSIONS.RECORDING_VIEW,
    PERMISSIONS.RECORDING_CREATE,

    PERMISSIONS.EVIDENCE_VIEW,

    PERMISSIONS.CLAIM_VIEW,
  ],

  [UserRole.OPERATOR]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ORDER_VIEW,

    PERMISSIONS.RECORDING_CREATE,

    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.EVIDENCE_VIEW,
  ],

  [UserRole.VIEWER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.ORDER_VIEW,
    PERMISSIONS.RECORDING_VIEW,
    PERMISSIONS.EVIDENCE_VIEW,
    PERMISSIONS.CLAIM_VIEW,
    PERMISSIONS.REPORT_VIEW,
  ],
};