version: '3.8'
services:
  api:
    build: .
    container_name: loss_defender_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
